/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbq_executor;

//import static dbq_executor.Executor.conn;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author domingos
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    private String query = "";
    private String result = "";
    public JanelaPrincipal() {
        
        initComponents();
        
        setSize(1240, 580);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JToggleButton();
        refreshBtn = new javax.swing.JToggleButton();
        crearBtn = new javax.swing.JToggleButton();
        executeAllBtn = new javax.swing.JToggleButton();
        executeSelectedBtn = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDeTabelas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        openExternarTxtQbtn = new javax.swing.JButton();
        separa1 = new javax.swing.JButton();
        saveToExternalTxtQbtn = new javax.swing.JButton();
        separa2 = new javax.swing.JButton();
        executeSelectedQueryQbtn = new javax.swing.JButton();
        separa3 = new javax.swing.JButton();
        executeAllQueryQbtn = new javax.swing.JButton();
        separa4 = new javax.swing.JButton();
        refreshQbtn = new javax.swing.JButton();
        separa5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        separa6 = new javax.swing.JButton();
        createDatabaseQbtn = new javax.swing.JButton();
        separa7 = new javax.swing.JButton();
        createTableQbtn = new javax.swing.JButton();
        separa8 = new javax.swing.JButton();
        createProcedQbtn = new javax.swing.JButton();
        separa9 = new javax.swing.JButton();
        createTriggerQbtn = new javax.swing.JButton();
        separa10 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        separa11 = new javax.swing.JButton();
        dropQbtn = new javax.swing.JButton();
        separa12 = new javax.swing.JButton();
        truncateQbtn = new javax.swing.JButton();
        separa13 = new javax.swing.JButton();
        deleteQbtn = new javax.swing.JButton();
        separa14 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        querTextAreaJta = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDatabases = new javax.swing.JList<>();
        useDatabaseBtn = new javax.swing.JButton();
        changeDbBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaProceduresJl = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaDeTriggers = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DBQ_Executor");
        setBackground(new java.awt.Color(1, 1, 1));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(64, 66, 71));
        jPanel1.setLayout(null);

        exitBtn.setBackground(new java.awt.Color(64, 66, 71));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(1100, 520, 133, 31);

        refreshBtn.setBackground(new java.awt.Color(64, 66, 71));
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jPanel1.add(refreshBtn);
        refreshBtn.setBounds(434, 520, 133, 31);

        crearBtn.setBackground(new java.awt.Color(64, 66, 71));
        crearBtn.setText("Clear ");
        crearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(crearBtn);
        crearBtn.setBounds(283, 520, 133, 31);

        executeAllBtn.setBackground(new java.awt.Color(64, 66, 71));
        executeAllBtn.setText("Execute Query");
        executeAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeAllBtnActionPerformed(evt);
            }
        });
        jPanel1.add(executeAllBtn);
        executeAllBtn.setBounds(147, 520, 118, 31);

        executeSelectedBtn.setBackground(new java.awt.Color(64, 66, 71));
        executeSelectedBtn.setText("Execute Select");
        executeSelectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeSelectedBtnActionPerformed(evt);
            }
        });
        jPanel1.add(executeSelectedBtn);
        executeSelectedBtn.setBounds(12, 520, 117, 31);

        jPanel2.setBackground(new java.awt.Color(64, 66, 71));

        jLabel2.setBackground(new java.awt.Color(224, 224, 224));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel2.setText("By : Domingos M. Fernando");

        jLabel3.setBackground(new java.awt.Color(224, 224, 224));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 55)); // NOI18N
        jLabel3.setText("Easy Query Executor");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 780, 120);

        jPanel5.setBackground(new java.awt.Color(148, 148, 148));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaDeTabelas.setBackground(new java.awt.Color(220, 215, 215));
        listaDeTabelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaDeTabelas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDeTabelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDeTabelasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaDeTabelas);

        jLabel1.setBackground(new java.awt.Color(126, 132, 152));
        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jLabel1.setText("Double Click to Select TB");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(783, 178, 220, 330);

        jPanel6.setBackground(new java.awt.Color(104, 104, 104));

        jToolBar1.setBackground(new java.awt.Color(64, 66, 71));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setToolTipText("");

        openExternarTxtQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Open.png"))); // NOI18N
        openExternarTxtQbtn.setToolTipText("Open content file in txt file.");
        openExternarTxtQbtn.setFocusable(false);
        openExternarTxtQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openExternarTxtQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(openExternarTxtQbtn);

        separa1.setEnabled(false);
        separa1.setFocusable(false);
        separa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        separa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                separa1ActionPerformed(evt);
            }
        });
        jToolBar1.add(separa1);

        saveToExternalTxtQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        saveToExternalTxtQbtn.setToolTipText("Save Query as txt file.");
        saveToExternalTxtQbtn.setFocusable(false);
        saveToExternalTxtQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveToExternalTxtQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(saveToExternalTxtQbtn);

        separa2.setEnabled(false);
        separa2.setFocusable(false);
        separa2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa2);

        executeSelectedQueryQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ExecuteSelected.png"))); // NOI18N
        executeSelectedQueryQbtn.setToolTipText("Execute Selected Query.");
        executeSelectedQueryQbtn.setFocusable(false);
        executeSelectedQueryQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        executeSelectedQueryQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        executeSelectedQueryQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeSelectedQueryQbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(executeSelectedQueryQbtn);

        separa3.setEnabled(false);
        separa3.setFocusable(false);
        separa3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        separa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                separa3ActionPerformed(evt);
            }
        });
        jToolBar1.add(separa3);

        executeAllQueryQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ExecuteAll.png"))); // NOI18N
        executeAllQueryQbtn.setToolTipText("Execute All Query on Terminal.");
        executeAllQueryQbtn.setFocusable(false);
        executeAllQueryQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        executeAllQueryQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        executeAllQueryQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeAllQueryQbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(executeAllQueryQbtn);

        separa4.setEnabled(false);
        separa4.setFocusable(false);
        separa4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa4);

        refreshQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Refresh.png"))); // NOI18N
        refreshQbtn.setToolTipText("Refresh All view.");
        refreshQbtn.setFocusable(false);
        refreshQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshQbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(refreshQbtn);

        separa5.setEnabled(false);
        separa5.setFocusable(false);
        separa5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa5);

        jButton11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton11.setText("|");
        jButton11.setEnabled(false);
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton11);

        separa6.setEnabled(false);
        separa6.setFocusable(false);
        separa6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa6);

        createDatabaseQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NewDatabe.png"))); // NOI18N
        createDatabaseQbtn.setToolTipText("Create new Database");
        createDatabaseQbtn.setFocusable(false);
        createDatabaseQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createDatabaseQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createDatabaseQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDatabaseQbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(createDatabaseQbtn);

        separa7.setEnabled(false);
        separa7.setFocusable(false);
        separa7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa7);

        createTableQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NewProcedure.png"))); // NOI18N
        createTableQbtn.setToolTipText("Create New Table");
        createTableQbtn.setFocusable(false);
        createTableQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createTableQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createTableQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTableQbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(createTableQbtn);

        separa8.setEnabled(false);
        separa8.setFocusable(false);
        separa8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa8);

        createProcedQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NewTable.png"))); // NOI18N
        createProcedQbtn.setToolTipText("Create new Procedure");
        createProcedQbtn.setFocusable(false);
        createProcedQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createProcedQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createProcedQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProcedQbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(createProcedQbtn);

        separa9.setEnabled(false);
        separa9.setFocusable(false);
        separa9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa9);

        createTriggerQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NewTrigger.png"))); // NOI18N
        createTriggerQbtn.setToolTipText("Create new Triger");
        createTriggerQbtn.setFocusable(false);
        createTriggerQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createTriggerQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createTriggerQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTriggerQbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(createTriggerQbtn);

        separa10.setEnabled(false);
        separa10.setFocusable(false);
        separa10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa10);

        jButton21.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton21.setText("|");
        jButton21.setEnabled(false);
        jButton21.setFocusable(false);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton21);

        separa11.setEnabled(false);
        separa11.setFocusable(false);
        separa11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa11);

        dropQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Drop.png"))); // NOI18N
        dropQbtn.setToolTipText("Drop table or database.");
        dropQbtn.setFocusable(false);
        dropQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dropQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(dropQbtn);

        separa12.setEnabled(false);
        separa12.setFocusable(false);
        separa12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa12);

        truncateQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Truncate.png"))); // NOI18N
        truncateQbtn.setToolTipText("Truncate");
        truncateQbtn.setFocusable(false);
        truncateQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        truncateQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(truncateQbtn);

        separa13.setEnabled(false);
        separa13.setFocusable(false);
        separa13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa13);

        deleteQbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        deleteQbtn.setToolTipText("Delete");
        deleteQbtn.setFocusable(false);
        deleteQbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteQbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(deleteQbtn);

        separa14.setEnabled(false);
        separa14.setFocusable(false);
        separa14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        separa14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(separa14);

        querTextAreaJta.setBackground(new java.awt.Color(64, 66, 71));
        querTextAreaJta.setColumns(20);
        querTextAreaJta.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        querTextAreaJta.setForeground(new java.awt.Color(254, 254, 254));
        querTextAreaJta.setRows(5);
        querTextAreaJta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(querTextAreaJta);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 128, 780, 380);

        jPanel7.setBackground(new java.awt.Color(148, 148, 148));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jListDatabases.setBackground(new java.awt.Color(220, 215, 215));
        jListDatabases.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jListDatabases.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListDatabases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDatabasesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListDatabases);

        useDatabaseBtn.setBackground(new java.awt.Color(64, 66, 71));
        useDatabaseBtn.setText("Use sel. DB");
        useDatabaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useDatabaseBtnActionPerformed(evt);
            }
        });

        changeDbBtn.setBackground(new java.awt.Color(64, 66, 71));
        changeDbBtn.setText("Change DB");
        changeDbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDbBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(useDatabaseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(changeDbBtn))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeDbBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useDatabaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(780, 0, 220, 170);

        jPanel8.setBackground(new java.awt.Color(148, 148, 148));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaProceduresJl.setBackground(new java.awt.Color(220, 215, 215));
        listaProceduresJl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaProceduresJl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaProceduresJl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaProceduresJlMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(listaProceduresJl);

        jLabel5.setBackground(new java.awt.Color(126, 132, 152));
        jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jLabel5.setText("Triggers");

        listaDeTriggers.setBackground(new java.awt.Color(220, 215, 215));
        listaDeTriggers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaDeTriggers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDeTriggers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDeTriggersMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(listaDeTriggers);

        jLabel6.setBackground(new java.awt.Color(126, 132, 152));
        jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        jLabel6.setText("Procedures");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(0, 138, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(1010, 0, 220, 510);

        jMenuBar1.setBackground(new java.awt.Color(64, 66, 71));
        jMenuBar1.setBorder(null);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeSelectedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeSelectedBtnActionPerformed
        // TODO add your handling code here:
        if (querTextAreaJta.getSelectedText() == null)
            result = "\nErro nenhum texto Selecionado";
        else
        {
            query = querTextAreaJta.getSelectedText();
            if (Executor.validarInstrucao(query))
                result = Executor.executarQuerySearch(query);
            else
                result = Executor.executarQuery(query);
        }
        querTextAreaJta.append(result);
    }//GEN-LAST:event_executeSelectedBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        //Conexao.closeConnection(conn, null, null);
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void executeAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeAllBtnActionPerformed
        // TODO add your handling code here:
        if (querTextAreaJta.getText() == null)
          result = "\nErro nenhum texto disponivel";
        else
        {
            query = querTextAreaJta.getText();
            if (Executor.validarInstrucao(query))
                result = Executor.executarQuerySearch(query);
            else
                result = Executor.executarQuery(query);
        }
        querTextAreaJta.append(result);
    }//GEN-LAST:event_executeAllBtnActionPerformed

    private void crearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBtnActionPerformed
        // TODO add your handling code here:
        querTextAreaJta.setText("");
    }//GEN-LAST:event_crearBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> strList = Executor.getDatabases();
        String[] str = new String[strList.size()];
        jListDatabases.removeAll();
        for (int i = 0; i < strList.size(); i++) {
            str[i] = strList.get(i);           
        }
        jListDatabases.setListData(str);
        
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void executeSelectedQueryQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeSelectedQueryQbtnActionPerformed
        // TODO add your handling code here:
        if (querTextAreaJta.getSelectedText() == null)
            result = "\nErro nenhum texto Selecionado";
        else
        {
            query = querTextAreaJta.getSelectedText();
            if (Executor.validarInstrucao(query))
                result = Executor.executarQuerySearch(query);
            else
                result = Executor.executarQuery(query);
        }
        querTextAreaJta.append(result);
    }//GEN-LAST:event_executeSelectedQueryQbtnActionPerformed

    private void separa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_separa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_separa1ActionPerformed

    private void separa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_separa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_separa3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void useDatabaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useDatabaseBtnActionPerformed
        // TODO add your handling code here:
        
        String tabList[];
        
        if (jListDatabases.getSelectedValue() != null)
        {
            jListDatabases.setEnabled(false);
            useDatabaseBtn.setEnabled(false);
            changeDbBtn.setEnabled(true);
            refreshBtn.setEnabled(false);
            createDatabaseQbtn.setEnabled(false);
            refreshQbtn.setEnabled(false);
            Conexao.setDatabase(jListDatabases.getSelectedValue().toString().trim());
            
            tabList = Executor.getDatabaseTable();
            listaDeTabelas.removeAll();
            listaDeTabelas.setListData(tabList);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Erro Nenhum item Selecionado");
        }
    }//GEN-LAST:event_useDatabaseBtnActionPerformed

    private void changeDbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDbBtnActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, " Não avera nenhuma base de dados Selecionada!\n "
                + "Continuar?") == 0)
        {
            jListDatabases.setEnabled(true);
            useDatabaseBtn.setEnabled(true);
            changeDbBtn.setEnabled(false);
            refreshBtn.setEnabled(true);
            createDatabaseQbtn.setEnabled(true);
            refreshQbtn.setEnabled(true);
            Conexao.setDatabase("");
            listaDeTabelas.setListData(new String[1]);
            listaDeTabelas.updateUI();
        }
    }//GEN-LAST:event_changeDbBtnActionPerformed

    private void listaDeTabelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeTabelasMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() >= 2)
            querTextAreaJta.append("\nSELECT * FROM " + listaDeTabelas.getSelectedValue() + ";");
    }//GEN-LAST:event_listaDeTabelasMouseClicked

    private void jListDatabasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDatabasesMouseClicked
        // TODO add your handling code here:
        String tabList[];
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() >= 2)
        {
            if (jListDatabases.getSelectedValue() != null)
            {
                jListDatabases.setEnabled(false);
                useDatabaseBtn.setEnabled(false);
                changeDbBtn.setEnabled(true);
                refreshBtn.setEnabled(false);
                createDatabaseQbtn.setEnabled(false);
                refreshQbtn.setEnabled(false);
                Conexao.setDatabase(jListDatabases.getSelectedValue().toString().trim());

                tabList = Executor.getDatabaseTable();
                listaDeTabelas.removeAll();
                listaDeTabelas.setListData(tabList);
                listaProceduresJl.removeAll();
                listaProceduresJl.setListData(Executor.getDatabaseProcedures());
                listaDeTriggers.removeAll();
                listaDeTriggers.setListData(Executor.getDatabaseTriggers());

            }
            else
            {
                JOptionPane.showMessageDialog(null, "Erro Nenhum item Selecionado");
            }
        }
        
    }//GEN-LAST:event_jListDatabasesMouseClicked

    private void executeAllQueryQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeAllQueryQbtnActionPerformed
        // TODO add your handling code here:
        if (querTextAreaJta.getText() == null)
          result = "\nErro nenhum texto disponivel";
        else
        {
            query = querTextAreaJta.getText();
            if (Executor.validarInstrucao(query))
                result = Executor.executarQuerySearch(query);
            else
                result = Executor.executarQuery(query);
        }
        querTextAreaJta.append(result);
    }//GEN-LAST:event_executeAllQueryQbtnActionPerformed

    private void refreshQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshQbtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> strList = Executor.getDatabases();
        String[] str = new String[strList.size()];
        jListDatabases.removeAll();
        for (int i = 0; i < strList.size(); i++) {
            str[i] = strList.get(i);           
        }
        jListDatabases.setListData(str);
    }//GEN-LAST:event_refreshQbtnActionPerformed

    private void createDatabaseQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDatabaseQbtnActionPerformed
        // TODO add your handling code here:
        querTextAreaJta.append("\nCREATE DATABASE <your_database_name>;");
    }//GEN-LAST:event_createDatabaseQbtnActionPerformed

    private void createTableQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTableQbtnActionPerformed
        // TODO add your handling code here:
        querTextAreaJta.append("\nCREATE TABLE <your_table_name>(Atrubute1 typeOfatribute1,Atrubute_n typeOfatribute_n);");
    }//GEN-LAST:event_createTableQbtnActionPerformed

    private void createProcedQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProcedQbtnActionPerformed
        // TODO add your handling code here:
        querTextAreaJta.append("\nDELIMITER //\nCREATE PROCEDURE <your_procedure_name>(PARAMETERS IN, OUT or INOUT)\n"
                + "BEGIN \n\n<body_of_your_routine>;\n"
                + "\nEND // \nDELIMITER;");
    }//GEN-LAST:event_createProcedQbtnActionPerformed

    private void createTriggerQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTriggerQbtnActionPerformed
        // TODO add your handling code here:
        querTextAreaJta.append("\nCREATE TRIGGER <your_trigger_name> <CONDITION TO TROW>\n"
                + "FOR EACH ROW\n"
                + "BEGIN \n\n<body_of_your_trigger>;\n"
                + "\nEND $$");
    }//GEN-LAST:event_createTriggerQbtnActionPerformed

    private void listaProceduresJlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaProceduresJlMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listaProceduresJlMouseClicked

    private void listaDeTriggersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeTriggersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeTriggersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeDbBtn;
    private javax.swing.JToggleButton crearBtn;
    private javax.swing.JButton createDatabaseQbtn;
    private javax.swing.JButton createProcedQbtn;
    private javax.swing.JButton createTableQbtn;
    private javax.swing.JButton createTriggerQbtn;
    private javax.swing.JButton deleteQbtn;
    private javax.swing.JButton dropQbtn;
    private javax.swing.JToggleButton executeAllBtn;
    private javax.swing.JButton executeAllQueryQbtn;
    private javax.swing.JToggleButton executeSelectedBtn;
    private javax.swing.JButton executeSelectedQueryQbtn;
    private javax.swing.JToggleButton exitBtn;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListDatabases;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<String> listaDeTabelas;
    private javax.swing.JList<String> listaDeTriggers;
    private javax.swing.JList<String> listaProceduresJl;
    private javax.swing.JButton openExternarTxtQbtn;
    private javax.swing.JTextArea querTextAreaJta;
    private javax.swing.JToggleButton refreshBtn;
    private javax.swing.JButton refreshQbtn;
    private javax.swing.JButton saveToExternalTxtQbtn;
    private javax.swing.JButton separa1;
    private javax.swing.JButton separa10;
    private javax.swing.JButton separa11;
    private javax.swing.JButton separa12;
    private javax.swing.JButton separa13;
    private javax.swing.JButton separa14;
    private javax.swing.JButton separa2;
    private javax.swing.JButton separa3;
    private javax.swing.JButton separa4;
    private javax.swing.JButton separa5;
    private javax.swing.JButton separa6;
    private javax.swing.JButton separa7;
    private javax.swing.JButton separa8;
    private javax.swing.JButton separa9;
    private javax.swing.JButton truncateQbtn;
    private javax.swing.JButton useDatabaseBtn;
    // End of variables declaration//GEN-END:variables
}
